CREATE SEQUENCE IF NOT EXISTS short_url_seq;

CREATE TABLE IF NOT EXISTS urls (
    id BIGINT PRIMARY KEY,
    short_url VARCHAR(10) UNIQUE NOT NULL,
    long_url TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);